### ISSUE TITLE
Returning not complete string.

### ISSUE THREAD

**Issue by sergiomonge10** [singlebrook/crypt#2]
I'm decrypting some value gave it by PHP, but I'm receiving incomplete information:

"09258,\"first_name\":\"TEST\",\"last_name\":\"TEST\",\"email\":\"test@gmail.com\"}"

It's missing some info: "{\"id\": "

**Comment by sbleon** [comment]
@sergiomonge10 we're not really maintaining this gem. But if you can add a failing test, or post some example code that demonstrates the problem in action, we may be able to look into it.

**Comment by sergiomonge10** [comment]
@sbleon I'm receiving this:

iv = "SauEynOFgpE="
value = "tffviLKCnQfhO+rDBDwWEUe5WAT1Iaj3tE5WEIc\/s39hyjCC8gCOCP\/amcMBla8QMadt5HifCN43PA34wx0IoWw\/N3FAfiPJWAiUD6NdNeqtP83jUhwbxlvq5IaC+DnkkVJ6BlloyxY0OwveZi7RvyVNeBkPPLgqAG8naaR6aGdXEm0XsgCbHvGPLXTI7J2xUyjWdKUcKZwnLSGrnDFxcnO6B7vBtDYxEcBzQEo7AmrONoeTideFmtqhqJmx4u09w2\/kePCj42mQKeZdT\/Eh5bwHM8J133wrmH0\/7U\/+Q17AOUs2qe\/CFP3IyMIXf3WxsYjW73\/VcKEkjqPfnK7sdI3YQidrHJZsuDxAkVWEsdzjyVhMfiTM0x1kianyN6qVtaValJ7rabqdPS9WD4W4XGna5ZW\/I7o\/IP8xRAUyniAxy1\/Rx94+CZ8+1akp808qUTJpuStE8IDCY6ScMtfqjJ7dz9nYUjWPpcT2T6arKlRZAWEVralVdXGm8BZS5kfYopiXfvA8A7q7F2mV3gYg0Yg7qE8QkZFkDl9IiVUYLOkC1hGCMf6RV04sNRdIiNlHZu+gbKToxVQ0htYOnEXb6spMgVmnWDSJcLnx9izmoaGqKYBIdEGI2ESD0xDOWdQ2Ei3UYtKVTkZnKqYlVP8lY1dIJWCtoFOepGta4RH6xWQxkZDK4KM5GyexdSeZFyLddvtuF5jjWJWEwHUGW1E1JXCiCytLwYO49auKDSK5WF749+S+WR4Ab8Bqdi8HkOa603LxrXpvvKDLMvqBORahNnHBu2\/2itY\/M40CKk3l5adxSdDBBuFNLBRk4faOfeyQ0IUPJ9fRLHB\/Ldp41jzDWcoMCVgVdMv3ybS3imsO0lrtqcdHfceNsQ\/iOkfmLFBEWxGQkNmNJuM+rZty8yCcZIUqHqUf2ZyWC6whLsv5LuwppckAmm2Ea1n97MMhF4Kc5IytSd6DpjBZTUSHxgbMBQrhqkwNIv5DDTCzHCs\/SD9KyQtkhJAinlCQrZ3\/sIePOqThAYnuoUIo6YGv4Ch8xe2aoYC6OSmLWoYLfLYm+qpbD+2gw7YSzO9WYFESl3XpEfdZi0icSwYmi7fMLktBb4GepSBlsUzr+gXJ6BD+OGpgqI2ieEJh10pCvo+hltpGKz5hx\/v6iDSe0RuohoK20WrES659MleSG0pnNwr7XMdbO8TgGMIYQmHP8dN3Jcr1qyDnQ5+6WYdRTgv6GEt\/mcvL7rH8VBLuqC6l6\/GRBeQFdviFTJBDr2eiccE91LAq1gEck1dAbf2mDHEL85Yb8fWKe95qj9oVrXLcO1NQo1uFez\/lfPE0T81HFTT14gIV4xmW5jkT0BIVChPd+bM\/AqIVyOlRnZRs6PRJABci0Yu00\/zsJAMpbioeVkVA5yXbIpoLsS3Om33t4T+1LAmeFSHHByq2O3PYy7K3yj+Ky4RA7y7hxnVzAfmYu7fj+4oJrK8CqXLCa48xEyUUIyMwKnD1bsMsRS+r31lKtXJgvG9cDrJlM4WhkkKgmQyn8zGkO\/dplKxjXYL4S7gDfk+zagj8ju08eTJGP\/KxuhbsWH\/5rLZtxwnhnqUKxsF0VynAPBvEcHKEwfSAm15ZDrcArHZAMU4OKkt47X2e\/M8G7Tmtuz587VGer9FOQ2ogxiJkcNPdLLCQYxwOPGWeNO+azrb9sT0sFzVE3SJbCAHdwn8awcUWr8dwcxiCSVCaqqBMdKglvmLN\/n+YMI2vFRpk9AQTDGoSxvSVzQBfW1SdD0xlglYPoPg9OKl8P6P3dM5\/yTeY5SxDRuHPHZYLqz0Q3gywkh7kcH0mDcCRywGnG1XHLYka5f0FV57A+TtY5wiHtZ1n+hOUpHOnOPStDgEcxy2KjSXNUgoIJyIZE1+dMGAowitDU5HFyoT6zyxhKRb9YgB5y1GazHs\/WFbEy1NkF8AqPQbSMWN+ZdHmns55GZEYZTZ+uT8wkwXPxris9JtHVN1QybpjYvd6I7Hq2iBTgpV0c3IIbZWkKiWfpRN1KVaras0mqdEkOOswhhZfiQmCYxWT+dRsFJplavCpUMmOQm7jL4efgi20BcghwwSjPAD8qts4cND\/Vg0YgmutBUzRM5OQMCKL2HQ9E0IfULEmCA=="
key = "QWpvK9XJhOr3a09zxquTQiHRIEQhikeg"

From PHP. 

Then I just use those variables 

blowfish = Crypt::Blowfish.new(key) 
value_decoded = Base64.decode64(value)
final_result = blowfish.decrypt_string(value_decoded)

and the information is not completed, I think It's because I'm not using the IV value

**Comment by sbleon** [comment]
@sergiomonge10, I’m not really familiar with the Blowfish code, but from
what I can tell it doesn’t allow you to specify an initialization vector.
From my limited understanding of Blowfish, you must supply your encryption
IV when decrypting. So you might be out of luck with this library.

I unfortunately don’t know much about this library. I’ve only made some
simplistic changes to add Ruby 1.9.x support.
